version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:22.9.0

jobs:
  install:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Debug .npmrc
          command: cat ~/.npmrc
      - run:
          name: Authenticate with registry
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  ci_pipeline:
    jobs:
      - install
      - deploy:
          requires:
            - install
